// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-UWJeooM7f7u-hvOR6p9RpNiUcUYbQUc',
    appId: '1:736150524813:web:1b511762cb3238cccee3c4',
    messagingSenderId: '736150524813',
    projectId: 'agrichain-official-app',
    authDomain: 'agrichain-official-app.firebaseapp.com',
    storageBucket: 'agrichain-official-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNnIXKYwIZMgGyFhfsXZLF9VBUlix3bnE',
    appId: '1:736150524813:android:f832153084a1b472cee3c4',
    messagingSenderId: '736150524813',
    projectId: 'agrichain-official-app',
    storageBucket: 'agrichain-official-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6939CSc2aF3HZBvuFX9zdPpGDBineg6U',
    appId: '1:736150524813:ios:5e9e29cb9a2c3637cee3c4',
    messagingSenderId: '736150524813',
    projectId: 'agrichain-official-app',
    storageBucket: 'agrichain-official-app.firebasestorage.app',
    iosBundleId: 'com.example.agrichain',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6939CSc2aF3HZBvuFX9zdPpGDBineg6U',
    appId: '1:736150524813:ios:5e9e29cb9a2c3637cee3c4',
    messagingSenderId: '736150524813',
    projectId: 'agrichain-official-app',
    storageBucket: 'agrichain-official-app.firebasestorage.app',
    iosBundleId: 'com.example.agrichain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-UWJeooM7f7u-hvOR6p9RpNiUcUYbQUc',
    appId: '1:736150524813:web:5cb0979c390eb82fcee3c4',
    messagingSenderId: '736150524813',
    projectId: 'agrichain-official-app',
    authDomain: 'agrichain-official-app.firebaseapp.com',
    storageBucket: 'agrichain-official-app.firebasestorage.app',
  );
}
