// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh45e2VAM5X5YVS8QyHC6CI5IsQGixp-Q',
    appId: '1:291941172263:web:aed6f35bac8e4694f57a02',
    messagingSenderId: '291941172263',
    projectId: 'agrichain-hackathon',
    authDomain: 'agrichain-hackathon.firebaseapp.com',
    storageBucket: 'agrichain-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh45e2VAM5X5YVS8QyHC6CI5IsQGixp-Q',
    appId: '1:291941172263:android:aed6f35bac8e4694f57a02',
    messagingSenderId: '291941172263',
    projectId: 'agrichain-hackathon',
    storageBucket: 'agrichain-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh45e2VAM5X5YVS8QyHC6CI5IsQGixp-Q',
    appId: '1:291941172263:ios:aed6f35bac8e4694f57a02',
    messagingSenderId: '291941172263',
    projectId: 'agrichain-hackathon',
    storageBucket: 'agrichain-hackathon.firebasestorage.app',
    iosBundleId: 'com.agrichain.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh45e2VAM5X5YVS8QyHC6CI5IsQGixp-Q',
    appId: '1:291941172263:macos:aed6f35bac8e4694f57a02',
    messagingSenderId: '291941172263',
    projectId: 'agrichain-hackathon',
    storageBucket: 'agrichain-hackathon.firebasestorage.app',
    iosBundleId: 'com.agrichain.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh45e2VAM5X5YVS8QyHC6CI5IsQGixp-Q',
    appId: '1:291941172263:windows:aed6f35bac8e4694f57a02',
    messagingSenderId: '291941172263',
    projectId: 'agrichain-hackathon',
    storageBucket: 'agrichain-hackathon.firebasestorage.app',
  );
}
